#!/usr/bin/env node
// Plugin CLI wrapper for {{PLUGIN_ID}}. Generated by img2 create-plugin-cli; do not edit by hand.
// Resolves the wrapper's own package.json to obtain img2Plugin metadata ({id, source, ref})
// and forwards argv to the harness's runPluginCli. Exit codes are forwarded verbatim.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { runPluginCli } from '@img2threejs/img2/plugin-cli'

const here = path.dirname(fileURLToPath(import.meta.url))
const pkgPath = path.resolve(here, '..', 'package.json')
if (!fs.existsSync(pkgPath)) {
  console.error('cli: package.json not found next to bin/cli.mjs; reinstall the wrapper')
  process.exit(1)
}
const packageUrl = pathToFileURL(pkgPath)

runPluginCli({ packageUrl, argv: process.argv.slice(2) }).then(
  (code) => process.exit(code),
  (err) => {
    console.error('cli: ' + (err && err.message))
    process.exit(1)
  },
)